FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

COPY ./Info.Platform.Contracts/*.csproj ./Info.Platform.Contracts/
COPY ./Info.Common/*.csproj ./Info.Common/
COPY ./Info.Command.Service/*.csproj ./Info.Command.Service/

RUN dotnet restore ./Info.Command.Service/Info.CommandService.csproj 

COPY . ./
RUN dotnet publish -c Release -o /app/out  ./Info.Command.Service/Info.CommandService.csproj

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet","Info.CommandService.dll" ]

