FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

COPY ./Info.Company.Contracts/*.csproj ./Info.Company.Contracts/
COPY ./Info.Platform.Contracts/*.csproj ./Info.Platform.Contracts/
COPY ./Info.Common/*.csproj ./Info.Common/
COPY ./Info.Platform.Service/*.csproj ./Info.Platform.Service/

RUN dotnet restore ./Info.Platform.Service/Info.PlatformService.csproj 

COPY . ./
RUN dotnet publish -c Release -o /app/out  ./Info.Platform.Service/Info.PlatformService.csproj

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet","Info.PlatformService.dll" ]

